# Importing Libraries

In [126]:
from samples import *
import util
import numpy as np
from sklearn.metrics import confusion_matrix

# Loading data

In [127]:
import doctest
doctest.testmod() # Test the interactive sessions in function comments
n = 5000
n_test = 1000
n_validation = 1000

items = loadDataFile("digitdata/trainingimages", n,28,28)
labels = loadLabelsFile("digitdata/traininglabels", n)

items_validation = loadDataFile("digitdata/validationimages", n_validation,28,28)
labels_validation = loadLabelsFile("digitdata/validationlabels", n_validation)

items_test = loadDataFile("digitdata/validationimages", n_test,28,28)
labels_test = loadLabelsFile("digitdata/validationlabels", n_test)

#Adding validation data to trainging data
items = items + items_validation
labels = labels + labels_validation

Printing Structure of a digit

In [128]:
print(items[0])
print(labels[0])

                            
                            
                            
                            
                            
                +++++##+    
        +++++######+###+    
       +##########+++++     
        #######+##          
        +++###  ++          
           +#+              
           +#+              
            +#+             
            +##++           
             +###++         
              ++##++        
                +##+        
                 ###+       
              +++###        
            ++#####+        
          ++######+         
        ++######+           
       +######+             
    ++######+               
    +####++                 
                            
                            
                            
5


In [129]:
items[0].pixels

[[0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  0,
  0,
  0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  2,
  2,
  0,
  0,
  0],
 [0,
  0,
  0

# Preprocessing data

In [130]:
x_train = []
for i in range(n+n_validation):
    x_train.append(list(items[i].getPixels()))


x_train= np.array(x_train)
y_train = np.array(labels)

x_train = x_train.reshape(n+n_validation,784) #784 = 28*28

x_test = []
for i in range(n_test):
    x_test.append(list(items_test[i].getPixels()))

x_test= np.array(x_test)
y_test = np.array(labels_test)

x_test = x_test.reshape(n_test,784)

print(x_train.shape)
print(y_train.shape)
print(y_train)
print(x_train)

(6000, 784)
(6000,)
[5 0 4 ... 0 8 9]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


# Learning with different Naive Bayes 

In [131]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, MultinomialNB,ComplementNB,BernoulliNB,CategoricalNB

# X_train, X_test, y_train, y_test = train_test_split(x, labels, test_size=0.2, random_state=0)
NBs = {'Multinomial NB':MultinomialNB(),'Complement NB':ComplementNB(),'Bernoulli NB':BernoulliNB(),'Gaussian NB':GaussianNB(),'Categorical NB':CategoricalNB(min_categories=3)}

for nbName,nb in NBs.items():
    fit = nb.fit(x_train, y_train)
    y_pred = fit.predict(x_test)
    sum = (y_test == y_pred).sum()
    accuracy = sum/len(x_test)
    print(f"{nbName}: {accuracy}")
    m = confusion_matrix(y_test, y_pred)
    print(f"Confusion Matrix: \n{m}")





Multinomial NB: 0.813
Confusion Matrix: 
[[ 78   0   0   0   0   0   1   0   6   0]
 [  0 119   0   4   0   0   1   0   2   0]
 [  2   1  96   1   0   0   1   3  10   2]
 [  0   2   1  88   0   2   3   3   4   4]
 [  1   0   0   0  74   0   4   0   5  26]
 [  2   0   1  10   2  60   2   3   5   2]
 [  3   0   3   0   2   4  73   0   2   0]
 [  0   5   0   1   2   0   0  74   4  13]
 [  0   2   2  10   4   0   0   0  67   4]
 [  0   1   0   1   4   0   0   0   4  84]]
Complement NB: 0.711
Confusion Matrix: 
[[ 77   0   0   0   0   0   5   0   3   0]
 [  0 122   0   3   0   0   1   0   0   0]
 [  8   5  84   3   0   0   8   4   3   1]
 [  1   4   4  85   0   0   1   8   1   3]
 [  2   6   0   0  74   3   3   4   0  18]
 [  6   2   1  24   1  35   5   9   2   2]
 [ 13   2   3   0   0   1  68   0   0   0]
 [  1  10   0   1   0   0   0  86   0   1]
 [  5  21   1  19   2   1   3   6  26   5]
 [  2   4   0   1   9   0   0  22   2  54]]
Bernoulli NB: 0.829
Confusion Matrix: 
[[ 77   0   0   0 

# Gaussian Naive Bayes

In [132]:


priors = [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1]
var_smooth = [0.4,0.2,0.1,0.15,0.01,0.001,0.0001,0.00001,0.000001,0.0000001]

best_acc = 0
best_parameters =''

for var in var_smooth:
    nb = GaussianNB(var_smoothing=var,priors=priors)
    fit = nb.fit(x_train, y_train)
    y_pred = fit.predict(x_test)
    sum = (y_test == y_pred).sum()
    accuracy = sum/len(x_test)
    if accuracy>best_acc:
        best_acc = accuracy
        best_parameters = f"var_smoothing = {var} \n Accuracy: {accuracy}"

print(best_parameters)

var_smoothing = 0.1 
 Accuracy: 0.784


# Bernoulli Naive Bayes

In [133]:
alpha = [0.000001,0.00001, 0.0001, 0.001, 0.1, 1, 10, 100,1000]
binarize =[0,1,2]
fit_prior = [True,False]

best_acc = 0
best_parameters =''

for a in alpha:
    for b in binarize:
        for f in fit_prior:
            nb = BernoulliNB(alpha=a,binarize=b,fit_prior=f)
            fit = nb.fit(x_train, y_train)
            y_pred = fit.predict(x_test)
            sum = (y_test == y_pred).sum()
            accuracy = sum/len(x_test)
            if accuracy>best_acc:
                best_acc = accuracy
                best_parameters = f"alpha = {a}, binarize= {b}, fit_prior = {f} \n Accuracy: {accuracy}"

        # m = confusion_matrix(y_test, y_pred)
        # print(f"Confusion Matrix: \n{m}")
print(best_parameters)


alpha = 1e-06, binarize= 0, fit_prior = True 
 Accuracy: 0.84


# Multinomial Naive Bayes

In [134]:
alpha = [0.0000001,0.000001,0.00001, 0.0001, 0.001, 0.1, 1, 10, 100,1000]
fit_prior = [True,False]
best_acc = 0
best_parameters =''
for a in alpha:
    for f in fit_prior:
        nb = MultinomialNB(alpha=a,fit_prior=f)
        fit = nb.fit(x_train, y_train)
        y_pred = fit.predict(x_test)
        sum = (y_test == y_pred).sum()
        accuracy = sum/len(x_test)
        if accuracy>best_acc:
            best_acc = accuracy
            best_parameters = f"alpha = {a}, fit_prior = {f} \n Accuracy: {accuracy}"

print(best_parameters)

alpha = 1e-07, fit_prior = True 
 Accuracy: 0.821


# Complement Naive Bayes 

In [135]:
alpha = [0.0000001,0.000001,0.00001, 0.0001, 0.001, 0.1, 1, 10, 100,1000,10000,1000000,100000000]
binarize =[0,1,2]
fit_prior = [True,False]
norm = [True, False]
best_acc = 0
best_parameters =''
for a in alpha:
    for f in fit_prior:
        for n in norm:
            nb = ComplementNB(alpha=a,fit_prior=f,norm=n)
            fit = nb.fit(x_train, y_train)
            y_pred = fit.predict(x_test)
            sum = (y_test == y_pred).sum()
            accuracy = sum/len(x_test)
            if accuracy>=best_acc:
                best_acc = accuracy
                best_parameters = f"alpha = {a},norm = {n}, fit_prior = {f} \n Accuracy: {accuracy}"

print(best_parameters)

alpha = 100000000,norm = False, fit_prior = False 
 Accuracy: 0.731


# Categorical Naive Bayes

In [136]:
alpha = [0.0000001,0.000001,0.00001, 0.0001, 0.001, 0.1, 1, 10, 100,1000,10000,1000000,100000000]
fit_prior = [True,False]
best_acc = 0
best_parameters =''
for a in alpha:
    for f in fit_prior:
        nb = CategoricalNB(min_categories=3,alpha=a,fit_prior=f)
        fit = nb.fit(x_train, y_train)
        y_pred = fit.predict(x_test)
        sum = (y_test == y_pred).sum()
        accuracy = sum/len(x_test)
        if accuracy>=best_acc:
            best_acc = accuracy
            best_parameters = f"alpha = {a}, fit_prior = {f} \n Accuracy: {accuracy}"

print(f"Best Parameters: {best_parameters}")

Best Parameters: alpha = 1e-07, fit_prior = False 
 Accuracy: 0.849
