# Importing Libraries

In [98]:
from samples import *
import util
import numpy as np
from sklearn.metrics import confusion_matrix

# Loading data

In [99]:
import doctest
doctest.testmod() # Test the interactive sessions in function comments
n = 451
n_test= 150
n_validation = 150

items = loadDataFile("facedata/facedatatrain", n,60,70)
labels = loadLabelsFile("facedata/facedatatrainlabels", n)

items_validation = loadDataFile("facedata/facedatavalidation", n_validation,60,70)
labels_validation = loadLabelsFile("facedata/facedatavalidationlabels", n_validation)

items_test = loadDataFile("facedata/facedatatest", n_test,60,70)
labels_test = loadLabelsFile("facedata/facedatatestlabels", n_test)

#Adding validation data to trainging data
items = items + items_validation
labels = labels + labels_validation

Printing Structure of a digit

In [100]:
print(items[0])

                                                            
                                                            
                             ###                            
                          ###   ###                         
                        ##         ####                     
                      ##               ###                  
                     #                    ###               
                    #                        #              
                    #                         #     ###     
                #   #                          #   #   #### 
               #   #                            ###         
              #    #          ##                 #          
              #    #         #  #                 #         
             #     #    #    #   ###               #        
             #     #   #     #  #   #              #        
            #      # ##      #  #   #              #        
            #       #   

In [101]:
print(items[0].pixels)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

# Preprocessing data

In [102]:
x_train = np.empty((n+n_validation,60,70))
for i in range(n+n_validation):
    for j in range(60):
        for k in range(70):
            x_train[i][j][k]=items[i].getPixels()[j][k]

x_test = np.empty((n_test,60,70))
for i in range(n_test):
    for j in range(60):
        for k in range(70):
            x_test[i][j][k]=items_test[i].getPixels()[j][k]

y_train = np.array(labels)
y_test = np.array(labels_test)

x_train = x_train.reshape(n+n_validation,4200) #784 = 28*28
x_test = x_test.reshape(n_test,4200)

print(x_train.shape)
print(y_train.shape)
print(y_train)
print(x_train)

(601, 4200)
(601,)
[1 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 1 0 0 0 0 1 1 1 1 0 0
 0 1 1 0 0 1 1 0 0 0 0 1 1 1 0 0 1 1 1 0 1 0 0 1 0 1 1 0 1 0 0 1 1 0 0 0 1
 1 0 1 1 1 0 1 1 1 1 1 1 0 1 0 0 0 0 1 1 1 1 0 1 0 1 1 1 1 1 0 0 0 0 1 1 0
 1 1 1 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 1 0 1 0 1 1 1 0 1 0 0 0 0 0 1 1 0 0 0
 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 0 1 1 0 1 1 0 0 0 0 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 1 1 1 1 1 0 1 1 1
 0 0 1 1 0 1 0 0 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 0 1 0 0 1 0 1 1
 1 1 0 0 1 0 1 1 0 0 0 0 1 1 0 1 0 0 0 1 1 0 1 1 1 1 0 0 1 0 0 0 1 1 0 0 0
 1 1 1 0 1 1 1 1 0 0 0 1 1 1 0 1 1 1 1 0 1 0 0 0 1 1 0 1 1 1 0 0 0 1 1 0 1
 1 1 1 1 0 1 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 1 1 0 0 1 0 0 1 0 0
 1 0 0 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 1 1 0 1 1 0 0 1 1 1 0 0 1 0 0 0 0 0 0
 1 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 1 0 0 1 1 0 1 0 0 1 1 1 0 1 1 0 0 1 1
 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 1 0 1 1 0 0 0 1 1
 1 1 1

# Learning with different Naive Bayes 

In [103]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, MultinomialNB,ComplementNB,BernoulliNB,CategoricalNB

# X_train, X_test, y_train, y_test = train_test_split(x, labels, test_size=0.2, random_state=0)
NBs = {'Multinomial NB':MultinomialNB(),'Complement NB':ComplementNB(),'Bernoulli NB':BernoulliNB(),'Gaussian NB':GaussianNB(),'Categorical NB': CategoricalNB()}

for nbName,nb in NBs.items():
    fit = nb.fit(x_train, y_train)
    y_pred = fit.predict(x_test)
    sum = (y_test == y_pred).sum()
    accuracy = sum/len(x_test)
    print(f"{nbName}: {accuracy}")
    m = confusion_matrix(y_test, y_pred)
    print(f"Confusion Matrix: \n{m}")


Multinomial NB: 0.88
Confusion Matrix: 
[[72  5]
 [13 60]]
Complement NB: 0.88
Confusion Matrix: 
[[72  5]
 [13 60]]
Bernoulli NB: 0.88
Confusion Matrix: 
[[67 10]
 [ 8 65]]
Gaussian NB: 0.8666666666666667
Confusion Matrix: 
[[69  8]
 [12 61]]
Categorical NB: 0.88
Confusion Matrix: 
[[67 10]
 [ 8 65]]


# Gaussian Naive Bayes

In [104]:
priors = [0.5,0.5]
var_smooth = [0.4,0.2,0.1,0.15,0.01,0.001,0.0001,0.00001,0.000001,0.0000001]

best_acc = 0
best_parameters =''

for var in var_smooth:
    nb = GaussianNB(var_smoothing=var,priors=priors)
    fit = nb.fit(x_train, y_train)
    y_pred = fit.predict(x_test)
    sum = (y_test == y_pred).sum()
    accuracy = sum/len(x_test)
    if accuracy>best_acc:
        best_acc = accuracy
        best_parameters = f"var_smoothing = {var} \n Accuracy: {accuracy}"

print(f"Best Parameters: {best_parameters}")

Best Parameters: var_smoothing = 0.1 
 Accuracy: 0.8733333333333333


# Bernoulli Naive Bayes

In [105]:
alpha = [0.000001,0.00001, 0.0001, 0.001, 0.1, 1, 10, 100,1000]
binarize =[0,1,2]
fit_prior = [True,False]
best_acc = 0
best_parameters =''
for a in alpha:
    for b in binarize:
        for f in fit_prior:
            nb = BernoulliNB(alpha=a,binarize=b,fit_prior=f)
            fit = nb.fit(x_train, y_train)
            y_pred = fit.predict(x_test)
            sum = (y_test == y_pred).sum()
            accuracy = sum/len(x_test)
            if accuracy>best_acc:
                best_acc = accuracy
                best_parameters = f"alpha = {a}, binarize= {b}, fit_prior = {f} \n Accuracy: {accuracy}"

        # m = confusion_matrix(y_test, y_pred)
        # print(f"Confusion Matrix: \n{m}")
print(f"Best Parameters: {best_parameters}")


Best Parameters: alpha = 1e-06, binarize= 0, fit_prior = True 
 Accuracy: 0.88


# Multinomial Naive Bayes

In [106]:
alpha = [0.0000001,0.000001,0.00001, 0.0001, 0.001, 0.1, 1, 10, 100,1000]
fit_prior = [True,False]
best_acc = 0
best_parameters =''
for a in alpha:
    for f in fit_prior:
        nb = MultinomialNB(alpha=a,fit_prior=f)
        fit = nb.fit(x_train, y_train)
        y_pred = fit.predict(x_test)
        sum = (y_test == y_pred).sum()
        accuracy = sum/len(x_test)
        if accuracy>best_acc:
            best_acc = accuracy
            best_parameters = f"alpha = {a}, fit_prior = {f} \n Accuracy: {accuracy}"

print(f"Best Parameters: {best_parameters}")

Best Parameters: alpha = 1000, fit_prior = False 
 Accuracy: 0.9


# Complement Naive Bayes 

In [107]:
alpha = [0.0000001,0.000001,0.00001, 0.0001, 0.001, 0.1, 1, 10, 100,1000,10000,1000000,100000000]
binarize =[0,1,2]
fit_prior = [True,False]
norm = [True, False]
best_acc = 0
best_parameters =''
for a in alpha:
    for f in fit_prior:
        for n in norm:
            nb = ComplementNB(alpha=a,fit_prior=f,norm=n)
            fit = nb.fit(x_train, y_train)
            y_pred = fit.predict(x_test)
            sum = (y_test == y_pred).sum()
            accuracy = sum/len(x_test)
            if accuracy>=best_acc:
                best_acc = accuracy
                best_parameters = f"alpha = {a},norm = {n}, fit_prior = {f} \n Accuracy: {accuracy}"

print(f"Best Parameters: {best_parameters}")

Best Parameters: alpha = 100000000,norm = False, fit_prior = False 
 Accuracy: 0.9


# Categorical Naive Bayes

In [108]:
alpha = [0.0000001,0.000001,0.00001, 0.0001, 0.001, 0.1, 1, 10, 100,1000,10000,1000000,100000000]
fit_prior = [True,False]
best_acc = 0
best_parameters =''
for a in alpha:
    for f in fit_prior:
        nb = CategoricalNB(alpha=a,fit_prior=f)
        fit = nb.fit(x_train, y_train)
        y_pred = fit.predict(x_test)
        sum = (y_test == y_pred).sum()
        accuracy = sum/len(x_test)
        if accuracy>=best_acc:
            best_acc = accuracy
            best_parameters = f"alpha = {a}, fit_prior = {f} \n Accuracy: {accuracy}"

print(f"Best Parameters: {best_parameters}")

Best Parameters: alpha = 10, fit_prior = False 
 Accuracy: 0.8933333333333333
