# Importing Libraries

In [39]:
from samples import *
import util
import numpy as np
from sklearn.metrics import confusion_matrix

# Loading data

In [40]:
import doctest
doctest.testmod() # Test the interactive sessions in function comments
n = 451
n_test= 150
n_validation = 150

items = loadDataFile("facedata/facedatatrain", n,60,70)
labels = loadLabelsFile("facedata/facedatatrainlabels", n)

items_validation = loadDataFile("facedata/facedatavalidation", n_validation,60,70)
labels_validation = loadLabelsFile("facedata/facedatavalidationlabels", n_validation)

items_test = loadDataFile("facedata/facedatatest", n_test,60,70)
labels_test = loadLabelsFile("facedata/facedatatestlabels", n_test)

#Adding validation data to training data
# items = items + items_validation
# labels = labels + labels_validation

#Adding validation data to testing data
items_test = items_test + items_validation
labels_test = labels_test + labels_validation

Printing Structure of a digit

In [41]:
print(items[0].getPixels())
print(labels[0])

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [42]:
# import matplotlib.pyplot as plt
# from scipy import ndimage

# rotated_img = ndimage.rotate(items[0].pixels, 90)
# plt.imshow(rotated_img,origin='lower')
# print(labels[0])
# print(items[0])

# Preprocessing data

In [43]:
x_train = np.empty((n,60,70))
for i in range(n):
    for j in range(60):
        for k in range(70):
            x_train[i][j][k]=items[i].getPixels()[j][k]

x_test = np.empty((n_test+n_validation,60,70))
for i in range(n_test+n_validation):
    for j in range(60):
        for k in range(70):
            x_test[i][j][k]=items_test[i].getPixels()[j][k]

y_train = np.array(labels)
y_test = np.array(labels_test)

x_train = x_train.reshape(n,4200) #784 = 28*28
x_test = x_test.reshape(n_test+n_validation,4200)

print(x_train.shape)
print(y_train.shape)
print(y_train)
print(x_train[0])

(451, 4200)
(451,)
[1 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 1 0 0 0 0 1 1 1 1 0 0
 0 1 1 0 0 1 1 0 0 0 0 1 1 1 0 0 1 1 1 0 1 0 0 1 0 1 1 0 1 0 0 1 1 0 0 0 1
 1 0 1 1 1 0 1 1 1 1 1 1 0 1 0 0 0 0 1 1 1 1 0 1 0 1 1 1 1 1 0 0 0 0 1 1 0
 1 1 1 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 1 0 1 0 1 1 1 0 1 0 0 0 0 0 1 1 0 0 0
 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 0 1 1 0 1 1 0 0 0 0 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 1 1 1 1 1 0 1 1 1
 0 0 1 1 0 1 0 0 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 0 1 0 0 1 0 1 1
 1 1 0 0 1 0 1 1 0 0 0 0 1 1 0 1 0 0 0 1 1 0 1 1 1 1 0 0 1 0 0 0 1 1 0 0 0
 1 1 1 0 1 1 1 1 0 0 0 1 1 1 0 1 1 1 1 0 1 0 0 0 1 1 0 1 1 1 0 0 0 1 1 0 1
 1 1 1 1 0 1 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 1 1 0 0 1 0 0 1 0 0
 1 0 0 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 1 1 0 1 1 0 0 1 1 1 0 0 1 0 0 0 0 0 0
 1 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 1 0 0 1 1 0 1 0 0 1 1 1 0 1 1 0 0 1 1
 0 1 0 0 1 0 1]
[0. 0. 0. ... 0. 0. 0.]


In [44]:
print(len(x_train[0]))

4200


# Learning with Support Vector Machine

In [45]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,confusion_matrix

svc = SVC(kernel='linear',random_state=1)
fit = svc.fit(x_train,y_train)
y_pred = fit.predict(x_test)
# print(svc.score(x_test,y_test))
print(accuracy_score(y_test,y_pred))

0.9166666666666666


In [46]:
cs = [0.1, 1, 10, 100, 1000]
for c in cs:
    svc = SVC(kernel='rbf',random_state=1, C=c).fit(x_train, y_train)
    y_pred = svc.predict(x_test)
    print(f"{c}: {accuracy_score(y_test,y_pred)}")
    print(confusion_matrix(y_test,y_pred))

0.1: 0.5333333333333333
[[160   0]
 [140   0]]
1: 0.9066666666666666
[[150  10]
 [ 18 122]]
10: 0.9233333333333333
[[151   9]
 [ 14 126]]
100: 0.9233333333333333
[[151   9]
 [ 14 126]]
1000: 0.9233333333333333
[[151   9]
 [ 14 126]]


## Trying different kernels

In [47]:
kernels = ['linear', 'rbf', 'poly']
print("kernel: accuracy")
for kernel in kernels:
  svc = SVC(kernel=kernel,random_state=1).fit(x_train, y_train)
  y_pred = svc.predict(x_test)
  print(f"{kernel}: {accuracy_score(y_test,y_pred)}")

kernel: accuracy
linear: 0.9166666666666666
rbf: 0.9066666666666666
poly: 0.68


## Trying different gammas

In [48]:
gammas = [0.1, 1, 10, 100, 'scale', 'auto']
print("gamma: accuracy")
for g in gammas:
  svc = SVC(gamma=g,random_state=1).fit(x_train, y_train)
  y_pred = svc.predict(x_test)
  print(f"{g}: {accuracy_score(y_test,y_pred)}")
  

gamma: accuracy
0.1: 0.5333333333333333
1: 0.5333333333333333
10: 0.5333333333333333
100: 0.5333333333333333
scale: 0.9066666666666666
auto: 0.9333333333333333


## Trying different degrees of polynomials

In [49]:
degrees = [0, 1, 2, 3, 4, 5, 6]
print("degree: accuracy")
for degree in degrees:
  svc = SVC(kernel='poly',random_state=1, degree=degree).fit(x_train, y_train)
  y_pred = svc.predict(x_test)
  print(f"{degree}: {accuracy_score(y_test,y_pred)}")

degree: accuracy
0: 0.5333333333333333
1: 0.92
2: 0.9333333333333333
3: 0.68
4: 0.49666666666666665
5: 0.47333333333333333
6: 0.47333333333333333


### Using the best hyperparameters from each of the previous tries

In [61]:
svc = SVC(kernel='poly',random_state=1, C=10,gamma='auto', degree=2).fit(x_train, y_train)
y_pred = svc.predict(x_test)
print(f"{accuracy_score(y_test,y_pred)}")

0.94


# Hyperparameters tuning

In [56]:
# Hyperparameters combinations
hyperparameters = [{
    "C":[0.1, 1, 10, 100],
    "kernel":['rbf','linear','poly','sigmoid'],
    "gamma":[0.1,'auto','scale'],
    "shrinking":[True,False],
    "probability":[False,True],
    
}
,{
    "C":[0.1, 1, 10, 100],
    "kernel":['poly'],
    "degree":[1,2,3,4,5,6,7,8,9]
}
]


## Using RandomizedSearchCV to search for best parameters
We used randomized to pick a random 10 hyperparameter combinations because exhaustive search require too much time to search for all combinations

In [64]:
# from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

# # search = GridSearchCV(estimator=svc,param_grid=hyperparameters,scoring='accuracy',verbose=5,n_jobs=-1)
search = RandomizedSearchCV(estimator=SVC(random_state=1),param_distributions=hyperparameters,n_iter=40,cv=5,scoring='accuracy',n_jobs=-1)

In [65]:
f = search.fit(x_train,y_train)

In [59]:
f.best_params_

{'shrinking': True,
 'probability': True,
 'kernel': 'rbf',
 'gamma': 'auto',
 'C': 100}

In [60]:
f.best_score_

0.8714529914529916